routes/web.php
<?php

use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CertificationController;
use App\Http\Controllers\Admin\CountryController;
use App\Http\Controllers\Admin\EmployeeController;
use App\Http\Controllers\Admin\FeatureController;
use App\Http\Controllers\Admin\GalleryController;
use App\Http\Controllers\Admin\HeaderController;
use App\Http\Controllers\Admin\MediaController;
use App\Http\Controllers\Admin\MetaController;
use App\Http\Controllers\Admin\MissionController;
use App\Http\Controllers\Admin\NoteController;
use App\Http\Controllers\Admin\PriceController;
use App\Http\Controllers\Admin\PriceTextController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\SectionController;
use App\Http\Controllers\Admin\ServicesController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ShortNewsController;
use App\Http\Controllers\Admin\SliderController;


use App\Http\Controllers\Admin\SocialController;
use App\Http\Controllers\Admin\SpecialtyController;
use App\Http\Controllers\Admin\SubSpecialtyController;
use App\Http\Controllers\Admin\UniversityController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\NewsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', [HomeController::class, 'home']);

//Route::get('lang/{lang}', [HomeController::class, 'switchLang'])->name('lang.switch');
//Route::get('admin_lang/{lang}', [AuthController::class, 'switchLang'])->name('admin_lang.switch');
Route::get('/admin_login', [AuthController::class, 'loginView'])->name('admin_login');
Route::post('/login', [AuthController::class, 'login']);
Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {

    Route::group(['middleware' => 'auth'], function () {
        ## About us Routes
        Route::resource('about', AboutController::class);

        ## ُEmployee Routes
        Route::resource('employees', EmployeeController::class);
        Route::get('/del_employee/{id}', [EmployeeController::class, 'destroy']);

        ## News Routes
        Route::resource('news', NewsController::class);
        Route::get('/del_news/{id}', [NewsController::class, 'destroy']);

        ## Short News Routes
        Route::resource('short_news', ShortNewsController::class);
        Route::get('/del_short_news/{id}', [ShortNewsController::class, 'destroy']);

        ## Missions Routes
        Route::resource('missions', MissionController::class);
        Route::get('/del_mission/{id}', [MissionController::class, 'destroy']);

        ## Missions Routes
        Route::resource('certifications', CertificationController::class);
        Route::get('/del_certification/{id}', [CertificationController::class, 'destroy']);

        ## questions Routes
        Route::resource('questions', QuestionController::class);
        Route::get('/del_question/{id}', [QuestionController::class, 'destroy']);

        ## Countries Routes
        Route::resource('countries', CountryController::class);
        Route::get('/del_country/{id}', [CountryController::class, 'destroy']);

        ## Specialty Routes
        Route::resource('specialties', SpecialtyController::class);
        Route::get('/del_specialty/{id}', [SpecialtyController::class, 'destroy']);

        ## Sub Specialty Routes
        Route::resource('sub_specialties', SubSpecialtyController::class);
        Route::get('/del_sub_specialty/{id}', [SubSpecialtyController::class, 'destroy']);

        ## Notes Routes
        Route::resource('notes', NoteController::class);
        Route::get('/del_note/{id}', [NoteController::class, 'destroy']);

        ## University Routes
        Route::resource('universities', UniversityController::class);
        Route::get('/del_university/{id}', [UniversityController::class, 'destroy']);


        ## University Notes Routes
        Route::resource('university_notes', NoteController::class);
        Route::get('/del_university_note/{id}', [NoteController::class, 'destroy']);



///////////////////////////////////////////////////////////////////////////////////////////
        ## headers Routes
        Route::resource('headers', HeaderController::class);
        Route::get('/download_header', [HeaderController::class, 'download']);

        ## gallery Routes
        Route::resource('services', ServicesController::class);
        Route::get('/del_service/{id}', [ServicesController::class, 'destroy']);

        ## gallery Routes
        Route::resource('gallery', GalleryController::class);
        Route::get('/del_gallery/{id}', [GalleryController::class, 'destroy']);

        ## features Routes
        Route::resource('features', FeatureController::class);
        Route::get('/del_feature/{id}', [FeatureController::class, 'destroy']);

        ## sliders Routes
        Route::resource('sliders', SliderController::class);
        Route::get('/del_slider/{id}', [SliderController::class, 'destroy']);
        Route::get('/download_slider/{id}', [SliderController::class, 'download']);


//        Route::resource('media', MediaController::class);

        ## price Routes
        Route::resource('prices', PriceController::class);
        Route::get('/del_price/{id}', [PriceController::class, 'destroy']);
        Route::resource('price_text', PriceTextController::class);

        ## whatsApp Routes
        Route::post('/update_whatsapp', [MediaController::class, 'updateWhatsapp']);
        Route::get('/edit_whatsapp', [MediaController::class, 'editWhatsapp']);

        ## call flyer Routes
        Route::post('/update_call', [MediaController::class, 'updateCall']);
        Route::get('/edit_call', [MediaController::class, 'editCall']);

        ## mail Routes
        Route::post('/update_mail', [MediaController::class, 'updateMail']);
        Route::get('/edit_mail', [MediaController::class, 'editMail']);

        ## phone Routes
        Route::post('/update_phone', [MediaController::class, 'updatePhone']);
        Route::get('/edit_phone', [MediaController::class, 'editPhone']);

        ## Social Routes
        Route::resource('social', SocialController::class);
        Route::get('/del_social/{id}', [SocialController::class, 'destroy']);

        ## Admins Routes
        Route::get('/users', [AdminController::class, 'users']);
        Route::get('/create_user', [AdminController::class, 'create_user']);

        Route::get('/logout', [AuthController::class, 'logout']);

    });
     Route::group(['middleware' => 'admin'], function () {
        Route::resource('settings', SettingController::class);
        Route::resource('metas', MetaController::class);

        ## sections name Routes
        Route::resource('sections', SectionController::class);
        Route::post('/update/{id}', [SettingController::class,'update']);


        ## Admins Routes
        Route::resource('admins', AdminController::class);
        Route::get('/admin_del/{id}', [AdminController::class, 'destroy']);

    });
});
//Route::get('/not_admin', [HomeController::class, 'not_admin']);
//Route::get('/{lang}', [HomeController::class, 'index']);

app/Models/Mission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mission extends Model
{
    use HasFactory;
    protected $fillable=['name','file'];
}

app/Http/Controllers/Admin/MissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Mission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class MissionController extends Controller
{
    public function index(){
        $missions=Mission::orderBy('created_at','desc')->paginate(15);
        return view ('admin.missions.index',['missions'=>$missions]);
    }

    public function create(){
        return view('admin.missions.create');
    }
    public function store(Request $request){
        if($request->file != ''){
            $path = 'images/missions/';
            $request->validate([
                'file' => 'mimes:csv,txt,xlx,xls,pdf,docx,pptx'
            ]);

            $file = $request->file;
            $imageExtension = $file->getClientOriginalExtension();
            $filename = time() . '.' . $imageExtension;
            $filename = $path.$filename;
            $file->move($path, $filename);



        }
        $mission=Mission::create([
            'name'      =>$request->name,
            'file'      =>$filename,
        ]);


        return redirect(route('admin_panel.missions.index'))->with('message', 'تمت الإضافة بنجاح');
    }
    public function edit(Request $request,$id){
        $mission=Mission::find($id);
        return view('admin.missions.edit',['mission'=>$mission]);
    }

    public function update(Request $request,$id){
        $mission=Mission::find($id);
        if($request->file != ''){
            $request->validate([
                'file' => 'mimes:csv,txt,xlx,xls,pdf,docx,pptx'
            ]);
            (File::exists($mission->file)) ? File::delete($mission->file) : Null;
            $path = 'images/missions/';

            $file = $request->file;
            $imageExtension = $file->getClientOriginalExtension();
            $filename = time() . '.' . $imageExtension;
            $filename = $path.$filename;
            $file->move($path, $filename);

            $mission->update([
                'file'      =>$filename
            ]);
        }

        $mission->update([
            'name'      =>$request->name
        ]);

        return redirect(route('admin_panel.missions.index'))->with('message', 'تم التعديل بنجاح');
    }
    public function destroy($id){
        $mission=Mission::find($id);
        (File::exists($mission->file)) ? File::delete($mission->file) : Null;
        $mission->delete();
        return redirect()->back()->with('message', 'تم الحذف بنجاح');
    }

}

resources/views/admin/missions/create.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        @include('admin.layouts.secondary_nav',['title'=>'لائحة البعثات ','sub_title'=>'إضافة بعثة'])
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="layout-spacing">

            <!-- Content -->
            <div class="col-12">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                    <h3 class="mt-4"> </h3>
                        <form class="g-3" method="post" action="{{route('admin_panel.missions.store')}}" enctype="multipart/form-data" >
                            @method('POST')
                            @csrf
                            @if ($errors->any())

                                <div class="alert alert-danger">

                                    <ul style="list-style: none;margin:0">

                                        @foreach ($errors->all() as $error)

                                            <li>{{ $error }}</li>

                                        @endforeach

                                    </ul>

                                </div>

                            @endif
                            @if(session()->has('message'))

                                    <div class="alert alert-success">

                                        {{ session()->get('message') }}

                                    </div>
                            @endif
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="inputAddress" class="form-label"> الملف </label>
                                    <input type="file" class="form-control"  placeholder="1234 Main St" name="file" required>
                                </div>

                                <div class="col-md-12">
                                    <label for="inputEmail4" class="form-label">الاسم </label>
                                    <input type="text" class="form-control"  name="name" required>
                                </div>


                                <div class="col-12">
                                    <div class=" mt-4">
                                        <button type="submit" class="btn btn-primary">إضافة</button>
                                    </div>
                                </div>

                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/missions/edit.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        @include('admin.layouts.secondary_nav',['title'=>'لائحة البعثات ','sub_title'=>'تعديل بعثة'])
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="layout-spacing">

            <!-- Content -->
            <div class="col-12">
                <div class="user-profile">
                    <div class="widget-content widget-content-area">
                        <h3 class="mt-4">  </h3>
                        <form class="row g-3" method="post" action="{{route('admin_panel.missions.update',$mission->id)}}" enctype="multipart/form-data" >
                            @method('PATCH')
                            @csrf
                            @if ($errors->any())

                                <div class="alert alert-danger">

                                    <ul style="list-style: none;margin:0">

                                        @foreach ($errors->all() as $error)

                                            <li>{{ $error }}</li>

                                        @endforeach

                                    </ul>

                                </div>

                            @endif
                            <div class="col-md-12">
                                <label for="inputAddress" class="form-label"> الملف  </label>
                                 <input type="file" class="form-control"  placeholder="1234 Main St" name="file" >
                                <a href="/{{$mission->file}}" target="_blank">{{$mission->file}}</a>

                            </div>

                            <div class="col-md-12">
                                <label for="inputEmail4" class="form-label">الاسم  </label>
                                <input type="text" class="form-control" value="{{$mission->name}}" name="name">
                            </div>

                            <div class="col-12">
                                <div class="">
                                <button type="submit" class="btn btn-primary">تعديل </button>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/missions/index.blade.php
@extends('admin.dashboard')

@section('content')
    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        @include('admin.layouts.secondary_nav',['title'=>'لائحة البعثات ','sub_title'=>''])
        <br>
        <!--  END BREADCRUMBS  -->

        <!-- Content -->
        <div class="col-12">
            <div class="user-profile mt-5">

                <div class="widget-content widget-content-area">
                    @if(session()->has('message'))

                        <div class="alert alert-success">

                            {{ session()->get('message') }}

                        </div>
                    @endif

                    <div class="table-responsive" id="t1">
                                <a class="btn btn-primary mb-2 me-4" href="{{route('admin_panel.missions.create')}}">إضافة بعثة </a>

                                <table id="myTable1" class="table table-striped table-bordered table-sm">
                                    <thead>
                                    <tr>
                                        <th class="text-center" scope="col"></th>
                                        <th scope="col">الاسم  </th>
                                        <th scope="col">الملف  </th>
                                        <th scope="col">تاريخ الإضافة </th>

                                        <th class="text-center" scope="col"></th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    <?php $counter=1;?>
                                    @foreach($missions as $mission)

                                        <tr>
                                            <td>
                                                <p class="text-center">{{$counter}}</p>
                                                <span class="text-success"></span>
                                                <?php $counter++;?>
                                            </td>

                                            <td>
                                                <p class="mb-0">{{$mission->name}}</p>
                                                <span class="text-success"></span>
                                            </td>
                                           <td>
                                                <a href="/{{$mission->file}}" target="_blank">{{$mission->file}}</a>
                                                <span class="text-success"></span>
                                            </td>
                                            <td>
                                                <p class="mb-0">{{$mission->created_at->toDateString()}}</p>
                                                <span class="text-success"></span>
                                            </td>

                                            <td class="text-center" width="10%">
                                                <div class="action-btns">
                                                    <a href="{{route('admin_panel.missions.edit',$mission->id)}}" class="action-btn btn-edit bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="{{trans('admin.edit')}} ">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>
                                                    </a>
                                                    <a href="/admin_panel/del_mission/{{$mission->id}}" class="action-btn btn-delete bs-tooltip" data-toggle="tooltip" data-placement="top" title="{{trans('admin.del')}} ">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                                    </a>

                                                </div>
                                            </td>
                                        </tr>

                                    @endforeach

                                    </tbody>

                                </table>

                            <div class="col-sm-12 col-md-7">
                                    {{ $missions->links() }}
                            </div>

                            </div>
                </div>
            </div>
        </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->




@endsection